### ISSUE TITLE
Error in colab notebook

### ISSUE THREAD

**Issue by david-samer** [camenduru/Wonder3D-colab#11]
In the instant-nsr-pl notebook I encountered an error while running the second block of code :
`%cd /content/Wonder3D/instant-nsr-pl
!python launch.py --config configs/neuralangelo-ortho-wmask.yaml --gpu 0 --train dataset.root_dir=/content/Wonder3D-test dataset.scene=owl `

Error:
`/content/Wonder3D/instant-nsr-pl
Traceback (most recent call last):
  File "/content/Wonder3D/instant-nsr-pl/launch.py", line 125, in <module>
    main()
  File "/content/Wonder3D/instant-nsr-pl/launch.py", line 38, in main
    import datasets
  File "/content/Wonder3D/instant-nsr-pl/datasets/__init__.py", line 16, in <module>
    from . import blender, colmap, dtu, ortho
  File "/content/Wonder3D/instant-nsr-pl/datasets/blender.py", line 14, in <module>
    from models.ray_utils import get_ray_directions
  File "/content/Wonder3D/instant-nsr-pl/models/__init__.py", line 16, in <module>
    from . import nerf, neus, geometry, texture
  File "/content/Wonder3D/instant-nsr-pl/models/nerf.py", line 9, in <module>
    from models.utils import chunk_batch
  File "/content/Wonder3D/instant-nsr-pl/models/utils.py", line 10, in <module>
    import tinycudann as tcnn
  File "/usr/local/lib/python3.10/dist-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/usr/local/lib/python3.10/dist-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib/python3.10/dist-packages/tinycudann_bindings/_75_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE`

![Screenshot 2024-04-20 174528](https://github.com/camenduru/Wonder3D-colab/assets/111081364/72681ce5-3ed0-4ed0-af94-a6111495f29d)

**Comment by jaymdq** [comment]
Same error over here. @david-samer did you find a solution to overcome this problem?
