### ISSUE TITLE
instant_nsr_pl_colab not working

### ISSUE THREAD

**Issue by fefespn** [camenduru/Wonder3D-colab#3]
anyone could use the instant_nsr_pl_colab ?? (regular colab not plus)

**Comment by EddieVec** [comment]
No, I get an error as it tries to load NerfAcc

`| Name  | Type             | Params
-------------------------------------------
0 | cos   | CosineSimilarity | 0
1 | model | NeuSModel        | 7.7 M 
-------------------------------------------
7.7 M     Trainable params
0         Non-trainable params
7.7 M     Total params
15.371    Total estimated model params size (MB)
2023-10-29 15:46:47.850741: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-29 15:46:47.850798: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-29 15:46:47.850840: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-29 15:46:49.871923: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Epoch 0: : 0it [00:00, ?it/s]Update finite_difference_eps to 0.027204705103003882
(  ●   ) NerfAcc: Setting up CUDA (This may take a few minutes the first time)^C`

**Comment by richvip93** [comment]
I have the same problem since yesterday, has anyone been able to solve it? thanks!

**Comment by nsarafianos** [comment]
After upgrading to colab plus it works just fine, it goes past this step and shows the training w/ the epochs etc. It needs more memory (keep the GPU as is and increase the System RAM)

**Comment by camenduru** [comment]
please try the new version

**Comment by newsun-boki** [comment]
I met a problem when I used V100, when I run 
`%cd /content/Wonder3D/instant-nsr-pl
!python launch.py --config configs/neuralangelo-ortho-wmask.yaml --gpu 0 --train dataset.root_dir=/content/Wonder3D/outputs/cropsize-192-cfg3.0 dataset.scene=owl`

it showed 
`/content/Wonder3D/instant-nsr-pl
Traceback (most recent call last):
  File "/content/Wonder3D/instant-nsr-pl/launch.py", line 125, in <module>
    main()
  File "/content/Wonder3D/instant-nsr-pl/launch.py", line 38, in main
    import datasets
  File "/content/Wonder3D/instant-nsr-pl/datasets/__init__.py", line 16, in <module>
    from . import blender, colmap, dtu, ortho
  File "/content/Wonder3D/instant-nsr-pl/datasets/blender.py", line 14, in <module>
    from models.ray_utils import get_ray_directions
  File "/content/Wonder3D/instant-nsr-pl/models/__init__.py", line 16, in <module>
    from . import nerf, neus, geometry, texture
  File "/content/Wonder3D/instant-nsr-pl/models/nerf.py", line 9, in <module>
    from models.utils import chunk_batch
  File "/content/Wonder3D/instant-nsr-pl/models/utils.py", line 10, in <module>
    import tinycudann as tcnn
  File "/usr/local/lib/python3.10/dist-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/usr/local/lib/python3.10/dist-packages/tinycudann/modules.py", line 59, in <module>
    raise EnvironmentError(f"Could not find compatible tinycudann extension for compute capability {system_compute_capability}.")
OSError: Could not find compatible tinycudann extension for compute capability 70.`

**Comment by newsun-boki** [comment]
I met a problem when I used V100, when I run
`%cd /content/Wonder3D/instant-nsr-pl !python launch.py --config configs/neuralangelo-ortho-wmask.yaml --gpu 0 --train dataset.root_dir=/content/Wonder3D/outputs/cropsize-192-cfg3.0 dataset.scene=owl`

it showed
```
/content/Wonder3D/instant-nsr-pl
Traceback (most recent call last):
  File "/content/Wonder3D/instant-nsr-pl/launch.py", line 125, in <module>
    main()
  File "/content/Wonder3D/instant-nsr-pl/launch.py", line 38, in main
    import datasets
  File "/content/Wonder3D/instant-nsr-pl/datasets/__init__.py", line 16, in <module>
    from . import blender, colmap, dtu, ortho
  File "/content/Wonder3D/instant-nsr-pl/datasets/blender.py", line 14, in <module>
    from models.ray_utils import get_ray_directions
  File "/content/Wonder3D/instant-nsr-pl/models/__init__.py", line 16, in <module>
    from . import nerf, neus, geometry, texture
  File "/content/Wonder3D/instant-nsr-pl/models/nerf.py", line 9, in <module>
    from models.utils import chunk_batch
  File "/content/Wonder3D/instant-nsr-pl/models/utils.py", line 10, in <module>
    import tinycudann as tcnn
  File "/usr/local/lib/python3.10/dist-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/usr/local/lib/python3.10/dist-packages/tinycudann/modules.py", line 59, in <module>
    raise EnvironmentError(f"Could not find compatible tinycudann extension for compute capability {system_compute_capability}.")
OSError: Could not find compatible tinycudann extension for compute capability 70.
```

**Comment by legel** [comment]
Had the same problem with trying to run the Google Colab without upgrading to Colab Pro (not enough RAM).
Then, had the same problem as @newsun-boki when trying to run on a V100.
I can confirm that if you switch the GPU to a T4 instance, then there is no problem and things run!
