### ISSUE TITLE
ImportError for libcudart.so.11.0 when Running launch.py in Google Colab

### ISSUE THREAD

**Issue by markuryy** [camenduru/Wonder3D-colab#9]
#### Environment:
- Google Colab
- CUDA version: 12.2 (as obtained from `nvcc --version` in Colab)

#### Issue Description:
I'm encountering an ImportError when trying to run cell 3 `launch.py` from the Wonder3D repository in a Google Colab environment. Despite following the installation instructions and ensuring dependencies are installed, the script fails with a missing CUDA runtime library error.

#### Steps to Reproduce:
1. Cloned the Google Colab environment.
2. Ran cell 3:
   ```bash
   %cd /content/Wonder3D/instant-nsr-pl
   !python launch.py --config configs/neuralangelo-ortho-wmask.yaml --gpu 0 --train dataset.root_dir=/content/Wonder3D/outputs/cropsize-192-cfg3.0 dataset.scene=dragonfly
   ```
3. Encountered the following error:
```
/content/Wonder3D/instant-nsr-pl
Traceback (most recent call last):
  File "/content/Wonder3D/instant-nsr-pl/launch.py", line 125, in <module>
    main()
  File "/content/Wonder3D/instant-nsr-pl/launch.py", line 38, in main
    import datasets
  File "/content/Wonder3D/instant-nsr-pl/datasets/__init__.py", line 16, in <module>
    from . import blender, colmap, dtu, ortho
  File "/content/Wonder3D/instant-nsr-pl/datasets/blender.py", line 14, in <module>
    from models.ray_utils import get_ray_directions
  File "/content/Wonder3D/instant-nsr-pl/models/__init__.py", line 16, in <module>
    from . import nerf, neus, geometry, texture
  File "/content/Wonder3D/instant-nsr-pl/models/nerf.py", line 9, in <module>
    from models.utils import chunk_batch
  File "/content/Wonder3D/instant-nsr-pl/models/utils.py", line 10, in <module>
    import tinycudann as tcnn
  File "/usr/local/lib/python3.10/dist-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/usr/local/lib/python3.10/dist-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

#### Attempts to Resolve:
- Installed `tiny-cuda-nn` as per the maintainer's instructions:
  ```bash
  !pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  ```
- Restarted the Colab runtime and re-ran the code.
- Checked for any updates or branches of `Wonder3D` that might be compatible with CUDA 12.2.

#### Additional Context:
It appears that `tiny-cuda-nn` requires CUDA 11.0, but Google Colab's environment is using CUDA 12.2. I'm unsure how to resolve this version mismatch or if there's a workaround available.

I'd appreciate any guidance or suggestions on how to proceed with running `Wonder3D` in Google Colab. Thank you!

**Comment by camenduru** [comment]
thanks for the info ❤ please try again
